### ISSUE TITLE
Bugtrapについて

### ISSUE THREAD

**Issue by surumeika** [hsdk123/Light.vn#4]
初めまして。こちらでサポートを行っていると画面に書いてあったのでこちらで質問させていただきます。同封してある筈のスクショ(少し写ってほしくないものがあったため、そこを切り取り、jpgにした以外はそのままです)の指示通りにエンターを押すとBugtrapが出てしまいます(スクショを取るためのプリントスクリーンボタンでも駄目だったのでおそらくボタンを押すこと自体が駄目なのかなと思います)。ドライバーをアップデートしてもプレイできませんでした。どうすればよいのでしょうか？
ちなみに動作環境はWindows１０です。
[Lightvnhasencounteredanerror_error_report_160616-150655.zip](https://github.com/hsdk123/Light.vn/files/317820/Lightvnhasencounteredanerror_error_report_160616-150655.zip)

**Comment by hsdk123** [comment]
初めまして、Light.vn製作者の炯淳です。ご連絡いただきありがとうございます！ゲームをこちら側でダウンロードし、内部のエンジンをアップデートしてみました。こちらの方はちゃんと作動しているか一度見て頂けますか？

リンク）https://www.dropbox.com/s/rt4bi5rbhbqgufm/Vampire%20or%E2%80%A6%E2%80%A6_160617.zip?dl=0

**Comment by surumeika** [comment]
DLしたところ、特に問題もなく進められました。ありがとうございます！

**Comment by hsdk123** [comment]
なによりです、もしまた何かありましたらいつだってご連絡ください！
